name: supabase_example
description: Supabase example with generated Prisma client
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dotenv: ^4.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  postgres: ^3.0.0
  prisma_flutter_connector:
    path: ../../

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.5.8
  json_serializable: ^6.8.0
